### ISSUE TITLE
getCurrentTime is not a function

### ISSUE THREAD

**Issue by ssansha** [yuhui/launchext-youtube-playback#28]
I am getting this error when triggering the rules of YouTube video play, pause, milestones and stop events
`Uncaught TypeError: e.getCurrentTime is not a function`
How to resolve this issue?

**Comment by yuhui** [comment]
@santosharma012, do you load the YouTube IFrame API script in your page too? I am aware of an issue where if the script is loaded in the page, and the script is also loaded from my extension, then that could cause this problem. If you have the script loaded in your page and also from my “Enable video playback tracking” action, try unchecking the checkbox in my action to load the YouTube IFrame API script, and see if that resolves your issue.

**Comment by ssansha** [comment]
Actually I'm trying to track youtube iframe videos inside a popup window. At first when we launch the video popup the tracking sometimes works but some times giving this getCurrentTime is not a function error. But when we closed that popup and relaunches it, than it is not triggering any of tracking rule and neither giving that error.
We are loading the script part only once. 
Is the popup functionality is not fitted for video tracking?

**Comment by yuhui** [comment]
Do you have a link that I can look at that shows your popup? If you want, you can email me at yuhui [at] yuhui [dot] sg

**Comment by ssansha** [comment]
We are still in testing and development phase that's why there is no link available to share. We are using swal2 library which is actually cuts the video iframe holder container from page DOM and places it to its own popup window which creates at the end of page body, and when we closes this, than the same iframe container puts back to original position in page DOM. 
Might be with this DOM manipulation, the video iframe, its tracking events gets lost that's why this is not working at second launch. 
Is there any way to reassign those tracking events to video iframe at second launch of popup?

**Comment by yuhui** [comment]
I'm not familiar with the swal2 library. It sounds like when it opens the popup, it reloads the YouTube video in the same web page. That might cause the YouTube IFrame API script to be loaded more than once, which can cause the error.
Unfortunately, I don't know if there's a way to reassign the tracking events.
