### ISSUE TITLE
Does not work in IE (11) due to nodeList.forEach method call

### ISSUE THREAD

**Issue by mijnschoen** [yuhui/launchext-youtube-playback#7]
**Describe the bug**
On IE11, the extension is not able to setup the players for the (iframe) elements, as an error is thrown: TypeError: Object doesn't support property or method 'forEach'

This is due to the nodeList type does nnot have a forEach method on IE.

**To Reproduce**
Use the extension on IE11 

**Expected behavior**
It should work on IE11.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Internet Explorer
 - Version: 11.1139.18362.0

**Comment by yuhui** [comment]
Superseded by #9 and #10
